### ISSUE TITLE
Build opinionated web browsers

### ISSUE THREAD

**Issue by tomayac** [WebView-CG/usage-and-challenges#4]
# Use case name

Build opinionated web browsers.

## Submitter(s)

Thomas Steiner ([@tomayac](https://github.com/tomayac))

## Motivation

Create web experiences that follow an opinionated style, for example, with removed ads or removed trackers.

## Stakeholders

Companies with opinionated views on how people should experience the web.

## Analysis

I looked at one concrete instance of such an opinionated web browser: [DuckDuckGo](https://duckduckgo.com/)'s privacy-focused [macOS browser](https://duckduckgo.com/mac) (careful, automatically downloads a 17.2MB `.dmg` file) is essentially a [`WKWebView`](https://developer.apple.com/documentation/webkit/wkwebview) with default- or opt-in-injected scripts for content blocking (e.g., [`contentblocker.js`](https://github.com/duckduckgo/iOS/blob/develop/Core/contentblocker.js)) and cookie consent (e.g., [autoconsent](https://github.com/duckduckgo/autoconsent)).

<img width="1792" alt="Screen Shot 2022-04-20 at 11 34 04" src="https://user-images.githubusercontent.com/145676/164202047-4a9a12d2-fa45-46ea-99eb-ca5a12262ee6.png">

## Related W3C deliverables and/or work items

N/A

## How is the issue solved in the Browser, and what’s more is needed?

Currently this use case is solved by injecting user scripts. One improvement I could imagine would be for companies to have a desire to keep their secrets. As you can see from the screenshot above, Web Inspector shows all these user scripts transparently.

**Comment by QingAn** [comment]
This is also related to #10 

Try to summarize, is it about supporting UserScript injection in WebView plus better confidentiality/privacy?

**Comment by tomayac** [comment]
#10 is related, yet different. 

- #4 (this issue): The objective is to build a browser that can display any webpage on the planet and where the user is in full control. An example is DuckDuckGo's browser on macOS.
- #10: The objective is to fit limited web content into an existing app where the user is not in full control. An example is an airline that uses the web-based seat allocation logic on both the app and the web. When seat allocation logic is displayed in a regular browser, the header and footer would be shown. When the seat allocation is displayed in the context of the app, user scripts would hide the header and footer. I have seen this pattern used in practice with [BA.com](https://www.britishairways.com/).

**Comment by muodov** [comment]
@tomayac thank you for raising this!
Our source code is mostly open, so keeping user scripts secret would probably not be the main concern for DuckDuckGo. We do face several platform-specific issues with WebView that we'd like to surface though. I'm currently collecting info on them internally, hope to follow up soon.

**Comment by muodov** [comment]
Judging by the [other use-case issues](https://github.com/WebView-CG/usage-and-challenges/issues/6#issuecomment-1119251776), and previous discussions, I understand that we are focusing on more granular, technical use-cases from developer perspective, as opposed to product-oriented or user-oriented ones. (@QingAn please correct me if I'm wrong :)

As such, I think this issue might be a bit too broad, since full-featured browsers have many components, and would likely need most of the features provided by WebViews. For example, both https://github.com/WebView-CG/usage-and-challenges/issues/12 and https://github.com/WebView-CG/usage-and-challenges/issues/6#issuecomment-1119251776 are also relevant to DuckDuckGo browsers, as well as several other issues that I'm going to write up.

If there is interest in the possibility of hiding injected scripts in the devtools, perhaps we could narrow this issue to that? Otherwise, would it make sense to close it in favour of more specific use-cases?

**Comment by QingAn** [comment]
@muodov Yes, sub-categorize and narrow down the use cases would be helpful.

**Comment by QingAn** [comment]
As discussed in 2022-07-06 meeting, @muodov and I suggest that it would be better to focus on more granular, technical use-cases, and so to close this issue. @tomayac we would like to ask your opinion whether it is ok to close this one and focus on #20 and more which will be submitted by @muodov ?

**Comment by tomayac** [comment]
Fine with me, especially since #20 was submitted by an actual DuckDuckGo employee. Closing my Issue.
